name: .NET Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PRESENTATION_PROJECTS_DIR: ./src/Presentation
  CLIENT_PROJECTS_DIR: ./src/Client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install MAUI workloads
        run: |
          dotnet workload install android
          dotnet workload install ios
          dotnet workload install maui

      - name: Build Web API
        run: dotnet build ${{ env.PRESENTATION_PROJECTS_DIR }}/Logistics.API/Logistics.API.csproj

      - name: Build Identity Server
        run: dotnet build ${{ env.PRESENTATION_PROJECTS_DIR }}/Logistics.IdentityServer/Logistics.IdentityServer.csproj

      - name: Build Admin App
        run: dotnet build ${{ env.CLIENT_PROJECTS_DIR }}/Logistics.AdminApp/Logistics.AdminApp.csproj

      - name: Create an empty appsettings.secrets.json file in the DriverApp project
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ env.CLIENT_PROJECTS_DIR }}/Logistics.DriverApp/appsettings.secrets.json
          contents: "{}"
          write-mode: preserve

      - name: Build Driver App
        run: dotnet build ${{ env.CLIENT_PROJECTS_DIR }}/Logistics.DriverApp/Logistics.DriverApp.csproj
